"""
Iterative / semiclassical Shor for ECDLP.

Replaces each multi-qubit counting register (j, k) with a **single recycled
qubit** plus mid-circuit measurement and classically-conditioned phase
corrections (Griffiths-Niu 1996 / Mosca-Ekert 1998). Trades the bulk inverse
QFT for dynamic-circuit phase corrections — far fewer qubits, same logical
depth, requires a backend supporting mid-circuit measurement + classical
feed-forward (IBM Heron r2/r3 are good; AerSimulator supports it natively).

Qubit comparison vs the standard two-register Shor (full t = m + Δ):
  - 8-bit (n=139), t=11 standard: ~32 qubits
  - 8-bit (n=139), t=11 iterative: ~17 qubits  (2 + m+1 + ancilla ≈ 2 + 9 + 9)

The point register and ancilla layout match :class:`RippleCarryOracle`'s
established convention, so :class:`ShorECDLPSolver`'s post-processing and
the new HNP-based extractor (``src/lattice_postprocess``) can both consume
the resulting counts without modification.

Reference: ``/tmp/lelli-quantum/google_semiclassical.py`` provides
Lelli's MIT-licensed implementation of the same technique; we re-derive
from Griffiths-Niu + the existing :class:`RippleCarryOracle` rather than
import directly, so we have a clean independent implementation for the
"true world record" track.

Status: initial scaffold. Builds the circuit and runs on noiseless Aer at
m ≤ 6. Real-hardware deployment needs the backend's ``dynamic_circuits``
feature enabled.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Optional

import numpy as np
from qiskit import ClassicalRegister, QuantumCircuit, QuantumRegister

from ecc import ECPoint, EllipticCurve
from shor_ecdlp import RippleCarryOracle, SubgroupIndexer


@dataclass(frozen=True)
class IterativePlan:
    n: int
    m: int
    t: int
    point_register_width: int
    ancilla_widths: dict[str, int]
    total_qubits: int
    standard_total_qubits: int  # what the non-iterative version would need
    qubit_savings: int


class IterativeShorECDLPSolver:
    """Iterative (semiclassical) two-register Shor for ECDLP.

    Same external interface as :class:`ShorECDLPSolver` but uses a
    single recycled qubit per counting register. The ``num_counting``
    parameter controls how many semiclassical bits are extracted per
    register (effective ``t``).

    Parameters
    ----------
    curve, G, Q, n
        Curve setup — same meaning as in :class:`ShorECDLPSolver`.
    oracle
        Currently only :class:`RippleCarryOracle` is supported. Dense
        oracle adaption is a follow-up.
    num_counting
        Effective ``t`` (number of phase bits per counting register).
        Choose so that ``M = 2^t ≥ 5·n`` to land in the sparse-peak
        regime where the HNP extractor recovers d-class genuinely.
    max_corrections
        Approximate-QFT truncation: each measured bit corrects only the
        ``max_corrections`` nearest subsequent bits. Setting this to
        ``None`` uses full QFT corrections; ``1`` matches Lelli's
        default for hardware fidelity reasons.
    """

    def __init__(
        self,
        curve: EllipticCurve,
        G: ECPoint,
        Q: ECPoint,
        n: int,
        *,
        oracle: Optional[RippleCarryOracle] = None,
        num_counting: int = 6,
        max_corrections: Optional[int] = 1,
    ):
        self.curve = curve
        self.G = G
        self.Q = Q
        self.n = n
        self.num_counting = num_counting
        self.max_corrections = max_corrections

        # Reuse the same oracle as the standard solver — its
        # ``controlled_add`` operation is the per-bit primitive we
        # iterate over.
        if oracle is None:
            ind = SubgroupIndexer(curve, G, n)
            oracle = RippleCarryOracle(ind)
        self.oracle = oracle
        if not isinstance(oracle, RippleCarryOracle):
            raise NotImplementedError(
                "iterative Shor currently only supports RippleCarryOracle"
            )
        if not self.oracle.indexer.contains(Q):
            raise ValueError("Q is not in the subgroup generated by G")

    def plan(self) -> IterativePlan:
        m = max(1, (self.n - 1).bit_length())
        pt_w = self.oracle.point_register_width()
        anc_widths = self.oracle.ancilla_widths()
        anc_total = sum(anc_widths.values())
        total_iterative = 2 + pt_w + anc_total
        total_standard = 2 * self.num_counting + pt_w + anc_total
        return IterativePlan(
            n=self.n,
            m=m,
            t=self.num_counting,
            point_register_width=pt_w,
            ancilla_widths=anc_widths,
            total_qubits=total_iterative,
            standard_total_qubits=total_standard,
            qubit_savings=total_standard - total_iterative,
        )

    # ------------------------------------------------------------------ build
    def build_circuit(self) -> QuantumCircuit:
        t = self.num_counting
        pt_w = self.oracle.point_register_width()
        anc_widths = self.oracle.ancilla_widths()

        # Two recycled qubits — one per counting register.
        j_qubit = QuantumRegister(1, "j")
        k_qubit = QuantumRegister(1, "k")
        pt_reg = QuantumRegister(pt_w, "pt")
        anc_regs = {name: QuantumRegister(w, name) for name, w in anc_widths.items()}

        # Classical register layout matches the standard solver:
        # [pt_bits | j_bits | k_bits]. Per-bit indices match too so
        # downstream bit-parsing code (extract / collective vote /
        # HNP) doesn't need a special branch.
        cr = ClassicalRegister(2 * t + pt_w, "cr")

        regs = [j_qubit, k_qubit, pt_reg, *anc_regs.values(), cr]
        qc = QuantumCircuit(*regs, name=f"ShorIter_n{self.n}")

        anc_qubits = sum(
            (list(anc_regs[name]) for name in anc_widths.keys()), []
        )

        def target_qubits(ctrl):
            return [ctrl] + list(pt_reg) + anc_qubits

        # ----- j-register: powers of G, MSB-first iteration -----
        powers_G: list[ECPoint] = []
        P = self.G
        for _ in range(t):
            powers_G.append(P)
            P = self.curve.add(P, P)

        for idx in range(t):
            bit_index = t - 1 - idx  # MSB first
            power_G = powers_G[bit_index]

            qc.reset(j_qubit)
            qc.h(j_qubit)

            if not power_G.is_infinity:
                G_idx = self.oracle.indexer.index_of(power_G)
                if G_idx != 0:
                    qc.append(
                        self.oracle.controlled_add(G_idx),
                        target_qubits(j_qubit[0]),
                    )

            # Approximate-QFT phase corrections from previously measured
            # bits closer than ``max_corrections``.
            correction_start = (
                max(0, idx - self.max_corrections)
                if self.max_corrections is not None
                else 0
            )
            for prev_idx in range(correction_start, idx):
                prev_bit_index = t - 1 - prev_idx
                angle = -math.pi / (2 ** (prev_bit_index - bit_index))
                prev_clbit = cr[pt_w + prev_bit_index]
                with qc.if_test((prev_clbit, 1)):
                    qc.p(angle, j_qubit[0])

            qc.h(j_qubit)
            qc.measure(j_qubit[0], cr[pt_w + bit_index])

        # ----- k-register: powers of Q -----
        powers_Q: list[ECPoint] = []
        P = self.Q
        for _ in range(t):
            powers_Q.append(P)
            P = self.curve.add(P, P)

        for idx in range(t):
            bit_index = t - 1 - idx
            power_Q = powers_Q[bit_index]

            qc.reset(k_qubit)
            qc.h(k_qubit)

            if not power_Q.is_infinity:
                Q_idx = self.oracle.indexer.index_of(power_Q)
                if Q_idx != 0:
                    qc.append(
                        self.oracle.controlled_add(Q_idx),
                        target_qubits(k_qubit[0]),
                    )

            correction_start = (
                max(0, idx - self.max_corrections)
                if self.max_corrections is not None
                else 0
            )
            for prev_idx in range(correction_start, idx):
                prev_bit_index = t - 1 - prev_idx
                angle = -math.pi / (2 ** (prev_bit_index - bit_index))
                prev_clbit = cr[pt_w + t + prev_bit_index]
                with qc.if_test((prev_clbit, 1)):
                    qc.p(angle, k_qubit[0])

            qc.h(k_qubit)
            qc.measure(k_qubit[0], cr[pt_w + t + bit_index])

        # ----- finally measure pt register -----
        for i in range(pt_w):
            qc.measure(pt_reg[i], cr[i])

        return qc


__all__ = ["IterativePlan", "IterativeShorECDLPSolver"]
